server:
  port: 90

security:
  secret: "secret"
  excluded_routes_prefixes:
    - "/api/public"
    - "/erp-api/public"
    - "/swagger"
  admin_redirect_url: /admin
  client_redirect_url: /client

postgres_data_source:
    host: "localhost"
    port: 5435
    user: "admin"
    password: "admin"
    db_name: "db"

smtp:
    company_name: "go-security"
    host: "smtp.gmail.com"
    port: 587
    user: user
    password: pwd

