server:
  port: 90

security:
  secret: "secret"
  excluded_routes_prefixes:
    - "/api/public"

postgres_data_source:
    host: "localhost"
    port: 5435
    user: "admin"
    password: "admin"
    db_name: "db"


